import type { SubscriptionPlan } from "@/lib/billing";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { getUploadLimit } from "@/lib/feature-gates";

export { canExportReports, canInviteTeamMembers, canRunAiAnalysis, canUsePortfolioMemory } from "@/lib/plan-access";
export type CompanyUsageState = { currentMonth: string; uploadCount: number };
const getCurrentMonthKey = () => { const now = new Date(); return `${now.getUTCFullYear()}-${String(now.getUTCMonth() + 1).padStart(2, "0")}`; };
const defaultUsage = (): CompanyUsageState => ({ currentMonth: getCurrentMonthKey(), uploadCount: 0 });
const normalizeUsage = (row: { current_month: unknown; upload_count: unknown }): CompanyUsageState => ({ currentMonth: typeof row.current_month === "string" && row.current_month.length > 0 ? row.current_month : getCurrentMonthKey(), uploadCount: typeof row.upload_count === "number" ? row.upload_count : 0 });
export const getCompanyUsage = async (companyId: string): Promise<CompanyUsageState> => { const supabase = await createSupabaseServerClient(); const { data, error } = await supabase.from("company_usage").select("current_month, upload_count").eq("company_id", companyId).maybeSingle(); if (error) throw new Error(`Unable to read company usage: ${error.message}`); if (!data) { const initial = defaultUsage(); const { error: upsertError } = await supabase.from("company_usage").upsert({ company_id: companyId, current_month: initial.currentMonth, upload_count: initial.uploadCount, updated_at: new Date().toISOString() }, { onConflict: "company_id" }); if (upsertError) throw new Error(`Unable to initialize company usage: ${upsertError.message}`); return initial; } const usage = normalizeUsage(data); if (usage.currentMonth !== getCurrentMonthKey()) { const reset = defaultUsage(); const { error: resetError } = await supabase.from("company_usage").update({ current_month: reset.currentMonth, upload_count: reset.uploadCount, updated_at: new Date().toISOString() }).eq("company_id", companyId); if (resetError) throw new Error(`Unable to reset company usage: ${resetError.message}`); return reset; } return usage; };
export const incrementUploadUsage = async (companyId: string, incrementBy = 1): Promise<CompanyUsageState> => { const current = await getCompanyUsage(companyId); const supabase = await createSupabaseServerClient(); const next = { currentMonth: getCurrentMonthKey(), uploadCount: current.uploadCount + incrementBy }; const { error } = await supabase.from("company_usage").upsert({ company_id: companyId, current_month: next.currentMonth, upload_count: next.uploadCount, updated_at: new Date().toISOString() }, { onConflict: "company_id" }); if (error) throw new Error(`Unable to increment company usage: ${error.message}`); return next; };
export const canUploadDocuments = (plan: SubscriptionPlan, currentUploadCount: number, incomingCount = 1) => { const limit = getUploadLimit(plan); return limit === null ? true : currentUploadCount + incomingCount <= limit; };
export const getUploadLimitForPlan = (plan: SubscriptionPlan) => getUploadLimit(plan);
