import { createHash, randomBytes } from "node:crypto";
import { createPrivilegedSupabaseClient } from "@/lib/security/privileged-access";
import { logSecurityEvent } from "@/lib/security/telemetry";

const FORBIDDEN = new Set(["billing.manage", "members.manage", "workspace.manage", "privileged.use"]);
const OWNER_ADMIN_ALLOWED = new Set(["project.read", "memory.read", "memory.write", "document.upload", "ai.execute"]);
const PM_ALLOWED = new Set(["project.read", "memory.read", "memory.write", "document.upload"]);

export type DelegationConstraints = { maxUses?: number; allowedUntil?: string; allowedActions?: string[]; allowedProjectIds?: string[]; allowedResourceTypes?: string[]; delegationDepth?: number; canDelegate?: boolean; [key: string]: unknown };
type DelegationInput = { [key: string]: unknown; parentGrantId?: string | null; parentDecisionId?: string | null; delegatorUserId?: string | null; delegatorAgentId?: string | null; delegateeUserId?: string | null; delegateeAgentId?: string | null; action: string; requestedPermission: string; workspaceId: string; projectId?: string | null; resourceType?: string | null; resourceId?: string | null; constraints?: DelegationConstraints; expiresAt?: string; depth?: number; delegatorRole?: "owner" | "admin" | "pm" | string; parentGrant?: { expires_at?: string | null; project_id?: string | null; requested_permission?: string | null } | null; parentConstraints?: DelegationConstraints; maxUses?: number; delegationToken?: string; actorUserId?: string | null; actorAgentId?: string | null; delegationId?: string; };

const hashToken = (t: string) => createHash("sha256").update(t).digest("hex");
const genToken = () => randomBytes(32).toString("base64url");

export function buildAuthorityLineage(input: DelegationInput) {
  return { parentGrantId: input.parentGrantId ?? null, parentDecisionId: input.parentDecisionId ?? null, delegatorUserId: input.delegatorUserId ?? null, delegatorAgentId: input.delegatorAgentId ?? null, delegateeUserId: input.delegateeUserId ?? null, delegateeAgentId: input.delegateeAgentId ?? null, action: input.action, requestedPermission: input.requestedPermission, workspaceId: input.workspaceId, projectId: input.projectId ?? null, scope: { resourceType: input.resourceType ?? null, resourceId: input.resourceId ?? null }, constraints: input.constraints ?? {}, issuedAt: new Date().toISOString(), expiresAt: input.expiresAt ?? new Date().toISOString(), depth: input.depth ?? 0 };
}
export function explainDelegationChain(lineage: ReturnType<typeof buildAuthorityLineage>) { return `Delegatee can execute because parent decision ${lineage.parentDecisionId ?? "n/a"} issued parent grant ${lineage.parentGrantId ?? "n/a"}, then delegation was derived under action ${lineage.action}.`; }

function assertDelegationRules(input: DelegationInput) {
  if (FORBIDDEN.has(input.action)) throw new Error("forbidden_action");
  if ((input.delegatorRole === "owner" || input.delegatorRole === "admin") && !OWNER_ADMIN_ALLOWED.has(input.action)) throw new Error("owner_admin_action_denied");
  if (input.delegatorRole === "pm" && !PM_ALLOWED.has(input.action)) throw new Error("pm_action_denied");
  if (input.delegatorRole === "pm" && !input.projectId) throw new Error("pm_requires_project_scope");
  if (input.expiresAt && input.parentGrant?.expires_at && new Date(input.expiresAt).getTime() > new Date(input.parentGrant.expires_at).getTime()) throw new Error("ttl_extension");
  if ((input.constraints?.delegationDepth ?? 0) > (input.parentConstraints?.delegationDepth ?? 1)) throw new Error("depth_exceeded");
  if (input.parentGrant?.project_id && input.projectId && input.parentGrant.project_id !== input.projectId) throw new Error("scope_broadening");
  if (input.parentGrant?.requested_permission && input.parentGrant.requested_permission !== input.requestedPermission) throw new Error("permission_broadening");
}

export async function issueDelegatedCapability(input: DelegationInput) { assertDelegationRules(input); const token = genToken(); const supabase = createPrivilegedSupabaseClient({ routeId: "governance.delegations.issue", operation: "issue_delegation", reason: "derived_authority", systemActor: "system", workspaceId: input.workspaceId, actorUserId: input.delegatorUserId ?? null }); const now = new Date().toISOString(); const constraints: DelegationConstraints = { ...(input.constraints ?? {}), maxUses: input.maxUses ?? 1 }; const payload = { parent_grant_id: input.parentGrantId ?? null, parent_decision_id: input.parentDecisionId ?? null, workspace_id: input.workspaceId, project_id: input.projectId ?? null, delegator_user_id: input.delegatorUserId ?? null, delegator_agent_id: input.delegatorAgentId ?? null, delegatee_user_id: input.delegateeUserId ?? null, delegatee_agent_id: input.delegateeAgentId ?? null, action: input.action, requested_permission: input.requestedPermission, resource_type: input.resourceType ?? null, resource_id: input.resourceId ?? null, constraints, status: "active", delegation_token_hash: hashToken(token), max_uses: input.maxUses ?? 1, uses_count: 0, expires_at: input.expiresAt, created_at: now, updated_at: now }; const { data, error } = await supabase.from("governance_delegations").insert(payload).select("*").single(); if (error) throw new Error(`issue delegation failed: ${error.message}`); await logSecurityEvent("delegated_capability_issued", { workspaceId: data.workspace_id, projectId: data.project_id, actorUserId: data.delegator_user_id, actorAgentId: data.delegator_agent_id, requested_permission: data.requested_permission, metadata: { delegationId: data.id, parentGrantId: data.parent_grant_id, parentDecisionId: data.parent_decision_id, delegateeUserId: data.delegatee_user_id, delegateeAgentId: data.delegatee_agent_id, action: data.action, status: data.status, depth: constraints.delegationDepth ?? 0 } }); return { delegation: data, delegationToken: token, lineage: buildAuthorityLineage({ ...input, expiresAt: input.expiresAt ?? new Date().toISOString(), depth: constraints.delegationDepth ?? 0 }) }; }
export async function validateDelegatedCapability(input: DelegationInput) { const supabase = createPrivilegedSupabaseClient({ routeId: "governance.delegations.validate", operation: "validate_delegation", reason: "pre_execution_validation", systemActor: "system", workspaceId: input.workspaceId, actorUserId: input.actorUserId ?? null }); const { data } = await supabase.from("governance_delegations").select("*").eq("delegation_token_hash", hashToken(input.delegationToken ?? "")).maybeSingle(); if (!data) return { ok: false, reason: "not_found" }; if (data.status !== "active") return { ok: false, reason: data.status, delegation: data }; if (new Date(data.expires_at).getTime() <= Date.now()) return { ok: false, reason: "expired", delegation: data }; if (data.uses_count >= data.max_uses) return { ok: false, reason: "max_uses_exceeded", delegation: data }; if (data.workspace_id !== input.workspaceId || (input.projectId && data.project_id && data.project_id !== input.projectId) || data.action !== input.action || data.requested_permission !== input.requestedPermission || (input.resourceType && data.resource_type && data.resource_type !== input.resourceType) || (input.resourceId && data.resource_id && data.resource_id !== input.resourceId) || (input.actorUserId && data.delegatee_user_id && data.delegatee_user_id !== input.actorUserId) || (input.actorAgentId && data.delegatee_agent_id && data.delegatee_agent_id !== input.actorAgentId)) return { ok: false, reason: "scope_mismatch", delegation: data }; return { ok: true, delegation: data }; }
export async function consumeDelegatedCapability(input: DelegationInput) { const validated = await validateDelegatedCapability(input); if (!validated.ok) return validated; const supabase = createPrivilegedSupabaseClient({ routeId: "governance.delegations.consume", operation: "consume_delegation", reason: "delegated_execution", systemActor: "system", workspaceId: input.workspaceId, actorUserId: input.actorUserId ?? null }); const { data } = await supabase.from("governance_delegations").update({ uses_count: validated.delegation.uses_count + 1, status: validated.delegation.uses_count + 1 >= validated.delegation.max_uses ? "consumed" : "active", consumed_at: validated.delegation.uses_count + 1 >= validated.delegation.max_uses ? new Date().toISOString() : null, updated_at: new Date().toISOString() }).eq("id", validated.delegation.id).eq("status", "active").select("*").maybeSingle(); if (!data) { await logSecurityEvent("delegated_capability_replay_attempt", { workspaceId: validated.delegation.workspace_id, projectId: validated.delegation.project_id, actorUserId: input.actorUserId ?? null, actorAgentId: input.actorAgentId ?? null, requested_permission: validated.delegation.requested_permission, metadata: { delegationId: validated.delegation.id, reason: "already_consumed_or_changed" } }); return { ok: false, reason: "replay_attempt", delegation: validated.delegation }; } await logSecurityEvent("delegated_capability_consumed", { workspaceId: data.workspace_id, projectId: data.project_id, actorUserId: input.actorUserId ?? null, actorAgentId: input.actorAgentId ?? null, requested_permission: data.requested_permission, metadata: { delegationId: data.id, parentGrantId: data.parent_grant_id, parentDecisionId: data.parent_decision_id, status: data.status } }); return { ok: true, delegation: data }; }
export async function revokeDelegatedCapability(input: DelegationInput) { const supabase = createPrivilegedSupabaseClient({ routeId: "governance.delegations.revoke", operation: "revoke_delegation", reason: "delegation_revocation", systemActor: "system", workspaceId: input.workspaceId, actorUserId: input.actorUserId ?? null }); const { data } = await supabase.from("governance_delegations").update({ status: "revoked", revoked_at: new Date().toISOString(), updated_at: new Date().toISOString() }).eq("id", input.delegationId).select("*").maybeSingle(); if (!data) return { ok: false, reason: "not_found" }; await logSecurityEvent("delegated_capability_revoked", { workspaceId: data.workspace_id, projectId: data.project_id, actorUserId: input.actorUserId ?? null, requested_permission: data.requested_permission, metadata: { delegationId: data.id } }); return { ok: true, delegation: data }; }
export async function expireDelegatedCapability(input: DelegationInput) { const supabase = createPrivilegedSupabaseClient({ routeId: "governance.delegations.expire", operation: "expire_delegation", reason: "delegation_expiry", systemActor: "system", workspaceId: input.workspaceId ?? null }); const { data } = await supabase.from("governance_delegations").update({ status: "expired", updated_at: new Date().toISOString() }).lt("expires_at", new Date().toISOString()).eq("status", "active").select("id,parent_grant_id,parent_decision_id,workspace_id,project_id,action,requested_permission,delegator_user_id,delegator_agent_id,delegatee_user_id,delegatee_agent_id"); for (const row of data ?? []) { await logSecurityEvent("delegated_capability_expired", { workspaceId: row.workspace_id, projectId: row.project_id, actorUserId: row.delegator_user_id, actorAgentId: row.delegator_agent_id, requested_permission: row.requested_permission, metadata: { delegationId: row.id, parentGrantId: row.parent_grant_id, parentDecisionId: row.parent_decision_id, action: row.action, status: "expired" } }); } return { ok: true, expiredCount: (data ?? []).length }; }
