import { createPublicKey, verify } from "node:crypto";
import { hashCapabilityClaim } from "@/lib/security/capability-claims";
import { logSecurityEvent } from "@/lib/security/telemetry";

export async function fetchIssuerMetadata(baseUrl: string) { const res = await fetch(`${baseUrl}/api/governance/trust/.well-known/capability-issuer`); const metadata = await res.json(); await logSecurityEvent("independent_verifier_metadata_fetched", { metadata: { issuer: metadata.issuerApp ?? null } }); return metadata; }
export async function fetchIssuerKeys(baseUrl: string) { const res = await fetch(`${baseUrl}/api/governance/trust/keys`); const keys = await res.json(); await logSecurityEvent("independent_verifier_keys_fetched", { metadata: { keyCount: keys.keys?.length ?? 0 } }); return keys; }
export function evaluateLocalVerifierTrustPolicy(input: { claim: any; expectedTrustDomain: string }) { return input.claim?.proof?.trustDomain === input.expectedTrustDomain ? { ok: true, reason: "local_policy_allow" } : { ok: false, reason: "unexpected_trust_domain" }; }
export function verifyClaimOffline(input: { claim: any; keySet: any[]; expectedTrustDomain: string }) { const local = evaluateLocalVerifierTrustPolicy({ claim: input.claim, expectedTrustDomain: input.expectedTrustDomain }); if (!local.ok) return { valid: false, reason: local.reason }; const key = input.keySet.find((k) => k.keyId === input.claim?.proof?.keyId && k.trustDomain === input.expectedTrustDomain); if (!key || key.status === "revoked") return { valid: false, reason: key ? "revoked_key" : "unknown_key" }; if (input.claim?.proof?.algorithm !== "Ed25519") return { valid: false, reason: "server_mediated_only_hmac" }; const unsigned = { ...input.claim, proof: undefined }; const verifier = key.publicJwk ? createPublicKey({ key: key.publicJwk, format: "jwk" }) : key.publicPem ? createPublicKey(key.publicPem) : null; if (!verifier) return { valid: false, reason: "missing_public_key" }; const ok = verify(null, Buffer.from(`${input.claim.proof.keyId}.${JSON.stringify(unsigned)}`), verifier, Buffer.from(input.claim.proof.signature, "base64url")); const result = ok ? { valid: true, reason: "verified", claimHash: hashCapabilityClaim(input.claim) } : { valid: false, reason: "signature_invalid" }; void logSecurityEvent(ok ? "independent_claim_verified" : "independent_claim_rejected", { metadata: { reason: result.reason, trustDomain: input.expectedTrustDomain } }); return result; }
export function explainIndependentVerification() { return { independentlyVerifiable: true, limitations: ["independent verification does not imply execution authorization", "HMAC claims remain server-mediated", "not public federation", "not DID/blockchain", "not AOC Protocol yet"] }; }
