import crypto from "node:crypto";
import type { VaultNutrient } from "../digestive/types";
import type { LearnedPatternType, PatternLearningContext, VaultLearnedPattern } from "./types";
import { loadInterventionHistory, persistInterventions, type InterventionPersistenceResult } from "./intervention-persistence";

export type InterventionType = "follow_up"|"escalation"|"technical_session"|"approval_request"|"vendor_coordination"|"customer_alignment"|"internal_alignment"|"risk_acceptance"|"recovery_action"|"governance_clarification"|"logistics_push"|"financial_escalation";
export type InterventionOutcome = "helped"|"failed"|"worsened"|"stalled"|"inconclusive"|"pending"|"recovered";
export type InterventionFatigueLevel = "none"|"low"|"medium"|"high";
export type InterventionEvidence = { nutrientId:string; excerpt:string; sourceArtifactId:string|null; timestamp:string };
export type InterventionFatigueProfile = { repeatedAttemptCount:number; failedAttemptCount:number; lastAttemptAt:string; fatigueLevel:InterventionFatigueLevel; fatigueReason:string; recommendedNextEscalation:string|null };
export type VaultIntervention = { id:string; workspaceId:string; projectId:string|null; targetPatternId:string|null; interventionType:InterventionType; title:string; summary:string; attemptedAt:string; actorUserId:string|null; evidenceReferences:InterventionEvidence[]; targetSignals:string[]; outcome:InterventionOutcome; efficacyScore:number; confidence:number; fatigueProfile:InterventionFatigueProfile; createdAt:string; updatedAt:string; outcomeReasons:string[]; timeToEffectDays:number|null; recurrenceAfterAttempt:number; severityDelta:number; confidenceDelta:number };
export type InterventionLearningOptions = { persist?: boolean; context?: PatternLearningContext };
export type InterventionLearningResult = { interventions: VaultIntervention[]; persistence: InterventionPersistenceResult };

const DETECTORS: Array<{type: InterventionType; patterns: RegExp[]}> = [
  { type: "follow_up", patterns: [/follow\s*up/i,/seguimiento/i,/solicit[oó]\s+actualizaci[oó]n/i,/pending\s+update\s+requested/i] },{ type: "escalation", patterns: [/escalat/i,/se\s+eleva\s+a\s+direcci[oó]n/i,/sponsor\s+intervention/i] },{ type: "technical_session", patterns: [/technical\s+session/i,/mesa\s+t[eé]cnica/i,/workshop/i,/guided\s+session/i,/validaci[oó]n\s+t[eé]cnica/i] },{ type: "approval_request", patterns: [/approval\s+requested/i,/pendiente\s+aprobaci[oó]n/i,/solicitud\s+de\s+aprobaci[oó]n/i,/visto\s+bueno/i] },{ type: "vendor_coordination", patterns: [/vendor\s+coordination/i,/td\s*synnex/i,/cisco/i,/manageengine/i,/supplier\s+follow-up/i,/vendor\s+release/i] },{ type: "financial_escalation", patterns: [/payment\s+pending/i,/\binvoice\b/i,/\bPO\b/i,/\bOC\b/i,/billing/i,/facturaci[oó]n/i,/presupuesto/i,/impedimento\s+financiero/i] },{ type: "governance_clarification", patterns: [/\bRACI\b/i,/ownership/i,/responsable/i,/decision\s+owner/i,/scope\s+clarification/i,/acuerdo/i,/minuta/i] },{ type: "recovery_action", patterns: [/resolved|unblocked|completed|recovered|habilitado|ya\s+se\s+complet[oó]/i] },{ type: "customer_alignment", patterns: [/customer\s+alignment/i,/alineaci[oó]n\s+con\s+cliente/i] },{ type: "internal_alignment", patterns: [/internal\s+alignment/i,/alineaci[oó]n\s+interna/i] },{ type: "risk_acceptance", patterns: [/risk\s+acceptance|accepted\s+risk/i] },{ type: "logistics_push", patterns: [/rma|shipment|dispatch|logistics/i] },
];
const PATTERN_MAP: Partial<Record<InterventionType, LearnedPatternType[]>> = { financial_escalation:["financial_friction_pattern"], technical_session:["recurring_dependency_pattern","governance_degradation_pattern"], vendor_coordination:["recurring_dependency_pattern","recurring_blocker_pattern"], approval_request:["governance_degradation_pattern","delivery_drift_pattern"], escalation:["escalation_trajectory_pattern","stakeholder_pressure_pattern"], recovery_action:["recovery_pattern","recurring_blocker_pattern"] };

export function detectInterventionsFromPatterns(nutrients: VaultNutrient[], patterns: VaultLearnedPattern[]): VaultIntervention[] { const now = new Date().toISOString(); const ints: VaultIntervention[] = []; for (const n of nutrients) { const txt = `${n.summary} ${n.evidence.map(e=>e.excerpt).join(" ")}`; for (const d of DETECTORS) if (d.patterns.some((p)=>p.test(txt))) { const linked = patterns.find((p)=>p.workspaceId===n.workspaceId && (p.projectId??"")===(n.projectId??"") && (PATTERN_MAP[d.type]?.includes(p.patternType) ?? true)) ?? null; ints.push({ id: crypto.randomUUID(), workspaceId:n.workspaceId, projectId:n.projectId, targetPatternId:linked?.id??null, interventionType:d.type, title:`${d.type} detected`, summary:n.summary.slice(0,220), attemptedAt:n.createdAt, actorUserId:n.evidence[0]?.actorUserId??null, evidenceReferences:[{nutrientId:n.id,excerpt:n.evidence[0]?.excerpt??n.summary,sourceArtifactId:n.evidence[0]?.sourceArtifactId??null,timestamp:n.createdAt}], targetSignals:[n.nutrientType], outcome:"pending", efficacyScore:50, confidence:0.45, fatigueProfile:{repeatedAttemptCount:1,failedAttemptCount:0,lastAttemptAt:n.createdAt,fatigueLevel:"none",fatigueReason:"",recommendedNextEscalation:null}, createdAt:now, updatedAt:now, outcomeReasons:["Pending post-intervention evidence window"], timeToEffectDays:null, recurrenceAfterAttempt:0, severityDelta:0, confidenceDelta:0 }); break; } }
  return learnInterventionEfficacy(ints, nutrients, patterns);
}

export function learnInterventionEfficacy(interventions: VaultIntervention[], nutrients: VaultNutrient[], patterns: VaultLearnedPattern[], historical: VaultIntervention[] = []) { return interventions.map((it)=> inferOutcome(it, nutrients, patterns, interventions, historical)); }

export async function learnAndPersistInterventionEfficacy(interventions: VaultIntervention[], nutrients: VaultNutrient[], patterns: VaultLearnedPattern[], options: InterventionLearningOptions = {}): Promise<InterventionLearningResult> {
  const historical = options.context ? await loadInterventionHistory(options.context, { projectId: options.context.projectId, limit: 500 }) : [];
  const learned = learnInterventionEfficacy(interventions, nutrients, patterns, historical);
  if (options.persist && options.context) return { interventions: learned, persistence: await persistInterventions(options.context, learned) };
  return { interventions: learned, persistence: { interventionsPersisted: 0, evidencePersisted: 0, outcomesPersisted: 0, method: "none" } };
}

function inferOutcome(it: VaultIntervention, nutrients: VaultNutrient[], patterns: VaultLearnedPattern[], all: VaultIntervention[], historical: VaultIntervention[]): VaultIntervention { const after = nutrients.filter((n)=>n.workspaceId===it.workspaceId && (n.projectId??"")===(it.projectId??"") && Date.parse(n.createdAt)>=Date.parse(it.attemptedAt)); const rec = after.filter((n)=>n.nutrientType==="recovery_signal").length; const esc = after.filter((n)=>n.nutrientType==="escalation_signal").length; const blockers = after.filter((n)=>["blocker_signal","dependency_signal"].includes(n.nutrientType)).length; const p = patterns.find((x)=>x.id===it.targetPatternId); const sevDelta = p ? ({low:1,medium:2,high:3,critical:4}[p.adaptiveScoring?.adaptiveSeverity??p.severity]-{low:1,medium:2,high:3,critical:4}[p.severity]) : 0; let outcome: InterventionOutcome = "pending"; const reasons:string[]=[]; if (rec>0 && esc===0) { outcome = rec>1?"recovered":"helped"; reasons.push("recovery evidence appears correlated after intervention"); } else if (esc>0 && rec===0) { outcome = "worsened"; reasons.push("escalation evidence increased after intervention"); } else if (blockers>=2 && rec===0) { outcome = "failed"; reasons.push("no improvement observed in blocker/dependency recurrence"); } else if (after.length===0) { outcome = "pending"; reasons.push("not enough post-intervention evidence yet"); } else if (rec>0 && esc>0) { outcome = "inconclusive"; reasons.push("conflicting recovery and escalation evidence"); } else { outcome = "stalled"; reasons.push("pattern remains active without meaningful trajectory change"); }
const same=[...historical,...all].filter((x)=>x.workspaceId===it.workspaceId&&(x.projectId??"")===(it.projectId??"")&&x.interventionType===it.interventionType&&x.targetPatternId===it.targetPatternId&&Date.parse(x.attemptedAt)<=Date.parse(it.attemptedAt)); const failedAttempts = same.filter((x)=>["failed","worsened","stalled"].includes(x.outcome)).length + (["failed","worsened","stalled"].includes(outcome)?1:0); const repeated = same.length + 1; const fatigueLevel: InterventionFatigueLevel = repeated>=4 && failedAttempts>=3?"high": repeated>=3?"medium": repeated>=2?"low":"none"; const recommendedNextEscalation = fatigueLevel==="high" ? (it.interventionType==="follow_up"?"escalation or governance_clarification":it.interventionType==="vendor_coordination"?"financial_escalation or sponsor intervention":"decision owner clarification or scope reset") : null; const score = outcome==="recovered"?90:outcome==="helped"?75:outcome==="stalled"?45:outcome==="inconclusive"?40:outcome==="pending"?50:outcome==="failed"?25:10; return { ...it, outcome, outcomeReasons:reasons, efficacyScore:score, confidence:Math.max(0.2,Math.min(0.95,0.45 + (rec*0.1) - (esc*0.08))), fatigueProfile:{repeatedAttemptCount:repeated,failedAttemptCount:failedAttempts,lastAttemptAt:it.attemptedAt,fatigueLevel,fatigueReason:fatigueLevel==="none"?"":`Repeated ${it.interventionType} attempts without clear recovery`,recommendedNextEscalation}, recurrenceAfterAttempt:blockers, severityDelta:sevDelta, confidenceDelta:0, timeToEffectDays:rec>0?0:null };
}
