import test from 'node:test'; import assert from 'node:assert/strict'
import { createInMemoryDashboardTaskLifecycleStore } from '../src/lib/dashboard/task-lifecycle/lifecycle-store.ts'
import { createLifecycleRecordFromEnvelope } from '../src/lib/dashboard/task-lifecycle/lifecycle-record-mapper.ts'
import { createStaticLiveConnector, normalizeConnectorRegistry } from '../src/lib/dashboard/live-adapter-connectors/connector-registry.ts'
import { validateLiveConnector } from '../src/lib/dashboard/live-adapter-connectors/connector-validator.ts'
import { selectExecutableLifecycles } from '../src/lib/dashboard/live-adapter-connectors/execution-selector.ts'
import { resolveExecutionPayload } from '../src/lib/dashboard/live-adapter-connectors/execution-payload-resolver.ts'
import { executeLifecycleThroughConnector } from '../src/lib/dashboard/live-adapter-connectors/connector-execution-engine.ts'
import { applyLiveExecutionResultToLifecycle, buildDashboardLiveExecutionReport } from '../src/lib/dashboard/live-adapter-connectors/execution-result-engine.ts'
import { runDashboardLiveAdapterConnectorRuntime } from '../src/lib/dashboard/live-adapter-connectors/live-adapter-connector-runtime.ts'

const NOW='2026-05-26T12:00:00.000Z'
const envelope=(id='env-1',adapter='jira')=>({id,adapter,actionId:`act-${id}`,payload:{adapter,title:'Title',description:'Desc',priority:'high',metadata:{}},mode:'ready',createdAt:NOW,executionStatus:'ready',warnings:[]})
const lifecycle=(id='env-1',adapter='jira')=>({...createLifecycleRecordFromEnvelope({envelope:envelope(id,adapter),now:NOW}),status:'ready_for_execution'})

test('1 static connector dry_run returns simulated', async()=>assert.equal((await createStaticLiveConnector({adapter:'jira'}).execute({payload:envelope().payload,lifecycle:lifecycle(),mode:'dry_run',now:NOW})).status,'simulated'))
test('2 static connector execute returns created external id', async()=>assert.match((await createStaticLiveConnector({adapter:'jira'}).execute({payload:envelope().payload,lifecycle:lifecycle(),mode:'execute',now:NOW})).externalTaskId,/^external:jira:/))
test('3 static connector deterministic failure', async()=>assert.equal((await createStaticLiveConnector({adapter:'jira',shouldFail:true,retryable:true}).execute({payload:envelope().payload,lifecycle:lifecycle(),mode:'execute',now:NOW})).retryable,true))
test('4 registry normalization filters invalid connectors',()=>assert.equal(Object.keys(normalizeConnectorRegistry({jira:createStaticLiveConnector({adapter:'jira'}),linear:{adapter:'linear'} })).length,1))
test('5 connector validation missing connector',()=>assert.equal(validateLiveConnector({adapter:'jira'}).status,'unavailable'))
test('6 connector validation adapter mismatch',()=>assert.equal(validateLiveConnector({adapter:'jira',connector:createStaticLiveConnector({adapter:'linear'})}).status,'invalid'))
test('7 selector picks ready lifecycle',()=>assert.equal(selectExecutableLifecycles({lifecycles:[lifecycle()]}).selected.length,1))
test('8 selector skips non-ready lifecycle',()=>assert.equal(selectExecutableLifecycles({lifecycles:[{...lifecycle(),status:'created'}]}).skipped[0].status,'skipped'))
test('9 selector filters requested lifecycle ids',()=>assert.equal(selectExecutableLifecycles({lifecycles:[lifecycle()],requestedLifecycleIds:['x']}).selected.length,0))
test('10 selector filters requested adapters',()=>assert.equal(selectExecutableLifecycles({lifecycles:[lifecycle()],requestedAdapters:['linear']}).selected.length,0))
test('11 selector respects maxExecutions',()=>assert.equal(selectExecutableLifecycles({lifecycles:[lifecycle('1'),lifecycle('2')],maxExecutions:1}).selected.length,1))
test('12 payload resolver valid payload',()=>assert.equal(resolveExecutionPayload(lifecycle()).valid,true))
test('13 payload resolver missing title',()=>assert.equal(resolveExecutionPayload({...lifecycle(),envelope:{...lifecycle().envelope,payload:{...lifecycle().envelope.payload,title:''}}}).valid,false))
test('14 execution engine success maps to executed',async()=>assert.equal((await executeLifecycleThroughConnector({lifecycle:lifecycle(),connector:createStaticLiveConnector({adapter:'jira'}),mode:'execute',now:NOW})).status,'executed'))
test('15 execution engine dry-run maps to simulated',async()=>assert.equal((await executeLifecycleThroughConnector({lifecycle:lifecycle(),connector:createStaticLiveConnector({adapter:'jira'}),mode:'dry_run',now:NOW})).status,'simulated'))
test('16 execution engine missing connector maps skipped',async()=>assert.equal((await executeLifecycleThroughConnector({lifecycle:lifecycle(),mode:'execute',now:NOW})).status,'skipped'))
test('17 execution engine retryable failure maps retry_scheduled',async()=>assert.equal((await executeLifecycleThroughConnector({lifecycle:lifecycle(),connector:createStaticLiveConnector({adapter:'jira',shouldFail:true,retryable:true}),mode:'execute',now:NOW})).status,'retry_scheduled'))
test('18 execution engine thrown error maps failed retryable',async()=>assert.equal((await executeLifecycleThroughConnector({lifecycle:lifecycle(),connector:{adapter:'jira',execute:async()=>{throw new Error('boom')}},mode:'execute',now:NOW})).retryable,true))
test('19 apply result updates lifecycle completed',async()=>{const store=createInMemoryDashboardTaskLifecycleStore();const l=lifecycle();await store.saveLifecycle(l);const a=await applyLiveExecutionResultToLifecycle({lifecycle:l,result:{lifecycleId:l.id,envelopeId:l.envelopeId,adapter:l.adapter,status:'executed',message:'ok',retryable:false},store,now:NOW});assert.equal(a.lifecycle.status,'execution_completed')})
test('20 apply retry increments retryCount',async()=>{const store=createInMemoryDashboardTaskLifecycleStore();const l=lifecycle();await store.saveLifecycle(l);const a=await applyLiveExecutionResultToLifecycle({lifecycle:l,result:{lifecycleId:l.id,envelopeId:l.envelopeId,adapter:l.adapter,status:'retry_scheduled',message:'retry',retryable:true},store,now:NOW});assert.equal(a.lifecycle.retryCount,1)})
test('21 apply skipped keeps lifecycle status',async()=>{const store=createInMemoryDashboardTaskLifecycleStore();const l=lifecycle();await store.saveLifecycle(l);const a=await applyLiveExecutionResultToLifecycle({lifecycle:l,result:{lifecycleId:l.id,envelopeId:l.envelopeId,adapter:l.adapter,status:'skipped',message:'skip',retryable:false},store,now:NOW});assert.equal(a.lifecycle.status,'ready_for_execution')})
test('22 report counts executed/simulated/skipped/failed/retry',()=>{const rep=buildDashboardLiveExecutionReport({generatedAt:NOW,mode:'execute',results:[{lifecycleId:'1',envelopeId:'1',adapter:'jira',status:'executed',message:'',retryable:false},{lifecycleId:'2',envelopeId:'2',adapter:'jira',status:'simulated',message:'',retryable:false},{lifecycleId:'3',envelopeId:'3',adapter:'jira',status:'skipped',message:'',retryable:false},{lifecycleId:'4',envelopeId:'4',adapter:'jira',status:'failed',message:'',retryable:false},{lifecycleId:'5',envelopeId:'5',adapter:'jira',status:'retry_scheduled',message:'',retryable:true}],events:[]});assert.equal(rep.retryScheduled,1)})
test('23 runtime end-to-end execute',async()=>{const store=createInMemoryDashboardTaskLifecycleStore();await store.saveLifecycle(lifecycle());const r=await runDashboardLiveAdapterConnectorRuntime({store,connectors:{jira:createStaticLiveConnector({adapter:'jira'})},mode:'execute',now:NOW});assert.equal(r.executed,1)})
test('24 runtime end-to-end dry_run',async()=>{const store=createInMemoryDashboardTaskLifecycleStore();await store.saveLifecycle(lifecycle());const r=await runDashboardLiveAdapterConnectorRuntime({store,connectors:{jira:createStaticLiveConnector({adapter:'jira'})},mode:'dry_run',now:NOW});assert.equal(r.simulated,1)})
test('25 runtime isolates connector failure and continues',async()=>{const store=createInMemoryDashboardTaskLifecycleStore();await store.saveLifecycle(lifecycle('a','jira'));await store.saveLifecycle(lifecycle('b','linear'));const r=await runDashboardLiveAdapterConnectorRuntime({store,connectors:{jira:createStaticLiveConnector({adapter:'jira'}),linear:createStaticLiveConnector({adapter:'linear',shouldFail:true})},mode:'execute',now:NOW});assert.equal(r.executed,1);assert.equal(r.failed,1)})
