import test from 'node:test'; import assert from 'node:assert/strict'
import { resolveDashboardApprovalPolicy, evaluateDashboardApprovalPolicy } from '../src/lib/dashboard/approval-workflow/approval-policy-engine.ts'
import { routeDashboardApprovalApprovers } from '../src/lib/dashboard/approval-workflow/approver-routing-engine.ts'
import { buildDashboardApprovalRequest } from '../src/lib/dashboard/approval-workflow/approval-request-builder.ts'
import { applyDashboardApprovalDecision } from '../src/lib/dashboard/approval-workflow/approval-decision-engine.ts'
import { deriveDashboardEnvelopeExecutionGate } from '../src/lib/dashboard/approval-workflow/approval-state-machine.ts'
import { buildDashboardApprovalWorkflowReport } from '../src/lib/dashboard/approval-workflow/approval-report-builder.ts'
import { runDashboardApprovalWorkflow } from '../src/lib/dashboard/approval-workflow/approval-workflow-runtime.ts'

const NOW = '2026-05-26T12:00:00.000Z'
const baseAction = { id:'act-1', type:'resolve_dependency', title:'Resolve dependency', description:'', priority:'medium', status:'proposed', ownerLane:'project_manager', executionLane:'dependency_management', affectedProjects:[], source:'dash', sla:{responseDueHours:1,resolutionDueHours:2,cadence:'daily'}, escalationRoute:{required:false}, evidenceRequired:[], rationale:'' }
const baseEnvelope = { id:'env-1', adapter:'internal_runtime', actionId:'act-1', payload:{adapter:'internal_runtime', title:'Do thing', description:'', priority:'normal', labels:[], dueHours:24, metadata:{}}, mode:'ready', createdAt:NOW, executionStatus:'ready', warnings:[] }

test('1 default policy resolution',()=>{ const p=resolveDashboardApprovalPolicy(); assert.equal(p.requireApprovalForCritical,true) })
test('2 policy expiry clamp',()=>{ const p=resolveDashboardApprovalPolicy({approvalExpiryHours:0}); assert.equal(p.approvalExpiryHours,1) })
test('3 dry run auto not required',()=>{ const e=evaluateDashboardApprovalPolicy({envelope:{...baseEnvelope,mode:'dry_run'},action:baseAction,policy:resolveDashboardApprovalPolicy()}); assert.equal(e.approvalRequired,false) })
test('4 ready mode requires approval',()=>{ const e=evaluateDashboardApprovalPolicy({envelope:baseEnvelope,action:baseAction,policy:resolveDashboardApprovalPolicy()}); assert.equal(e.approvalRequired,true) })
test('5 external adapter requires approval',()=>{ const e=evaluateDashboardApprovalPolicy({envelope:{...baseEnvelope,adapter:'jira'},action:baseAction,policy:resolveDashboardApprovalPolicy()}); assert.equal(e.approvalRequired,true) })
test('6 critical action requires PMO approval',()=>{ const lanes=routeDashboardApprovalApprovers({envelope:baseEnvelope,action:{...baseAction,priority:'critical'},evaluation:{approvalRequired:true,riskLevel:'critical',reasons:[],requiredApproverLanes:[]}}); assert.ok(lanes.includes('pmo_director')) })
test('7 financial action routes finance lead',()=>{ const lanes=routeDashboardApprovalApprovers({envelope:baseEnvelope,action:{...baseAction,type:'review_financial_exposure'},evaluation:{approvalRequired:true,riskLevel:'critical',reasons:[],requiredApproverLanes:[]}}); assert.ok(lanes.includes('finance_lead')) })
test('8 executive decision routes executive sponsor',()=>{ const lanes=routeDashboardApprovalApprovers({envelope:baseEnvelope,action:{...baseAction,type:'review_executive_decision'},evaluation:{approvalRequired:true,riskLevel:'high',reasons:[],requiredApproverLanes:[]}}); assert.ok(lanes.includes('executive_sponsor')) })
test('9 technical/dependency lane routes technical lead',()=>{ const lanes=routeDashboardApprovalApprovers({envelope:baseEnvelope,action:baseAction,evaluation:{approvalRequired:true,riskLevel:'high',reasons:[],requiredApproverLanes:[]}}); assert.ok(lanes.includes('technical_lead')) })
test('10 external adapter routes system owner',()=>{ const lanes=routeDashboardApprovalApprovers({envelope:{...baseEnvelope,adapter:'jira'},action:baseAction,evaluation:{approvalRequired:true,riskLevel:'high',reasons:[],requiredApproverLanes:[]}}); assert.ok(lanes.includes('system_owner')) })
test('11 approval request pending',()=>{ const r=buildDashboardApprovalRequest({envelope:baseEnvelope,action:baseAction,evaluation:{approvalRequired:true,riskLevel:'medium',reasons:['x'],requiredApproverLanes:['project_manager']},policy:resolveDashboardApprovalPolicy(),now:NOW}); assert.equal(r.status,'pending') })
test('12 approval request not_required',()=>{ const r=buildDashboardApprovalRequest({envelope:baseEnvelope,action:baseAction,evaluation:{approvalRequired:false,riskLevel:'low',reasons:['x'],requiredApproverLanes:[]},policy:resolveDashboardApprovalPolicy(),now:NOW}); assert.equal(r.status,'not_required') })
test('13 approve decision transitions to approved',()=>{ const req=buildDashboardApprovalRequest({envelope:baseEnvelope,action:baseAction,evaluation:{approvalRequired:true,riskLevel:'medium',reasons:['x'],requiredApproverLanes:['project_manager']},policy:resolveDashboardApprovalPolicy(),now:NOW}); const r=applyDashboardApprovalDecision({request:req,decision:{requestId:req.id,decision:'approve',decidedBy:'u',decidedAt:NOW},now:NOW}); assert.equal(r.status,'approved') })
test('14 reject decision transitions to rejected',()=>{ const req=buildDashboardApprovalRequest({envelope:baseEnvelope,action:baseAction,evaluation:{approvalRequired:true,riskLevel:'medium',reasons:['x'],requiredApproverLanes:['project_manager']},policy:resolveDashboardApprovalPolicy(),now:NOW}); const r=applyDashboardApprovalDecision({request:req,decision:{requestId:req.id,decision:'reject',decidedBy:'u',decidedAt:NOW},now:NOW}); assert.equal(r.status,'rejected') })
test('15 request changes transitions to changes_requested',()=>{ const req=buildDashboardApprovalRequest({envelope:baseEnvelope,action:baseAction,evaluation:{approvalRequired:true,riskLevel:'medium',reasons:['x'],requiredApproverLanes:['project_manager']},policy:resolveDashboardApprovalPolicy(),now:NOW}); const r=applyDashboardApprovalDecision({request:req,decision:{requestId:req.id,decision:'request_changes',decidedBy:'u',decidedAt:NOW},now:NOW}); assert.equal(r.status,'changes_requested') })
test('16 expired request transitions to expired',()=>{ const req={...buildDashboardApprovalRequest({envelope:baseEnvelope,action:baseAction,evaluation:{approvalRequired:true,riskLevel:'medium',reasons:['x'],requiredApproverLanes:['project_manager']},policy:resolveDashboardApprovalPolicy(),now:NOW}),expiresAt:'2026-05-01T00:00:00.000Z'}; const r=applyDashboardApprovalDecision({request:req,now:NOW}); assert.equal(r.status,'expired') })
test('17 execution gate approved executable',()=>{ const g=deriveDashboardEnvelopeExecutionGate({id:'approval:1',envelopeId:'1',actionId:'a',adapter:'jira',actionTitle:'x',priority:'medium',ownerLane:'project_manager',requestedAt:NOW,status:'approved',riskLevel:'low',requiredApproverLanes:[],reasons:[]}); assert.equal(g.executable,true) })
test('18 execution gate pending blocked',()=>{ const g=deriveDashboardEnvelopeExecutionGate({id:'approval:1',envelopeId:'1',actionId:'a',adapter:'jira',actionTitle:'x',priority:'medium',ownerLane:'project_manager',requestedAt:NOW,status:'pending',riskLevel:'low',requiredApproverLanes:[],reasons:[]}); assert.equal(g.blocked,true) })
test('19 runtime with approval pending blocks envelope',()=>{ const r=runDashboardApprovalWorkflow({envelopes:[baseEnvelope],actions:[baseAction],now:NOW}); assert.ok(r.blockedEnvelopeIds.includes('env-1')) })
test('20 runtime with approval decision unlocks envelope',()=>{ const reqId='approval:env-1'; const r=runDashboardApprovalWorkflow({envelopes:[baseEnvelope],actions:[baseAction],decisions:[{requestId:reqId,decision:'approve',decidedBy:'u',decidedAt:NOW}],now:NOW}); assert.ok(r.executableEnvelopeIds.includes('env-1')) })
test('21 runtime with dry_run envelope executable',()=>{ const r=runDashboardApprovalWorkflow({envelopes:[{...baseEnvelope,mode:'dry_run'}],actions:[baseAction],now:NOW}); assert.ok(r.executableEnvelopeIds.includes('env-1')) })
test('22 report counts blocked envelopes',()=>{ const req={id:'approval:env-1',envelopeId:'env-1',actionId:'act-1',adapter:'jira',actionTitle:'x',priority:'medium',ownerLane:'project_manager',requestedAt:NOW,status:'pending',riskLevel:'high',requiredApproverLanes:['project_manager'],reasons:['x']}; const rep=buildDashboardApprovalWorkflowReport({generatedAt:NOW,envelopes:[baseEnvelope],requests:[req],decisions:[]}); assert.equal(rep.blockedCount,1) })
test('23 report no approval required summary',()=>{ const req={id:'approval:env-1',envelopeId:'env-1',actionId:'act-1',adapter:'jira',actionTitle:'x',priority:'medium',ownerLane:'project_manager',requestedAt:NOW,status:'not_required',riskLevel:'low',requiredApproverLanes:[],reasons:['x']}; const rep=buildDashboardApprovalWorkflowReport({generatedAt:NOW,envelopes:[{...baseEnvelope,mode:'dry_run'}],requests:[req],decisions:[]}); assert.ok(rep.executiveSummary.includes('No approval workflow required')) })
test('24 latest decision wins',()=>{ const reqId='approval:env-1'; const r=runDashboardApprovalWorkflow({envelopes:[baseEnvelope],actions:[baseAction],decisions:[{requestId:reqId,decision:'reject',decidedBy:'u',decidedAt:'2026-05-26T10:00:00.000Z'},{requestId:reqId,decision:'approve',decidedBy:'u',decidedAt:'2026-05-26T11:00:00.000Z'}],now:NOW}); assert.equal(r.requests[0].status,'approved') })
test('25 existing request preserved',()=>{ const existing={id:'approval:env-1',envelopeId:'env-1',actionId:'act-1',adapter:'internal_runtime',actionTitle:'old',priority:'medium',ownerLane:'project_manager',requestedAt:'2026-05-20T00:00:00.000Z',status:'rejected',riskLevel:'high',requiredApproverLanes:['pmo_director'],reasons:['Manually rejected.']}; const r=runDashboardApprovalWorkflow({envelopes:[baseEnvelope],actions:[baseAction],existingRequests:[existing],now:NOW}); assert.equal(r.requests[0].status,'rejected'); assert.deepEqual(r.requests[0].reasons,['Manually rejected.']) })
