import test from 'node:test'; import assert from 'node:assert/strict'
import { buildLifecycleId, createLifecycleRecordFromEnvelope, mergeApprovalIntoLifecycle } from '../src/lib/dashboard/task-lifecycle/lifecycle-record-mapper.ts'
import { createInMemoryDashboardTaskLifecycleStore } from '../src/lib/dashboard/task-lifecycle/lifecycle-store.ts'
import { deriveExecutionReadinessTransition, deriveLifecycleTransitionFromApproval } from '../src/lib/dashboard/task-lifecycle/lifecycle-transition-engine.ts'
import { buildEventFromTransition, buildLifecycleEvent } from '../src/lib/dashboard/task-lifecycle/lifecycle-audit-engine.ts'
import { reconcileDashboardTaskLifecycle } from '../src/lib/dashboard/task-lifecycle/lifecycle-reconciliation-engine.ts'
import { runDashboardTaskLifecyclePersistence } from '../src/lib/dashboard/task-lifecycle/task-lifecycle-runtime.ts'
import { buildDashboardTaskLifecycleReport } from '../src/lib/dashboard/task-lifecycle/lifecycle-report-builder.ts'

const NOW='2026-05-26T12:00:00.000Z'
const env={id:'env-1',adapter:'jira',actionId:'act-1',payload:{adapter:'jira',title:'x',description:'',priority:'high',labels:[],dueHours:24,metadata:{}},mode:'ready',createdAt:NOW,executionStatus:'ready',warnings:[]}
const dry={...env,id:'env-2',mode:'dry_run'}
const req=(status)=>({id:'approval:'+env.id,envelopeId:env.id,actionId:env.actionId,adapter:env.adapter,actionTitle:'x',priority:'medium',ownerLane:'project_manager',requestedAt:NOW,status,riskLevel:'medium',requiredApproverLanes:[],reasons:[]})

test('1 buildLifecycleId',()=>assert.equal(buildLifecycleId({envelopeId:'e'}),'task-lifecycle:e'))
test('2 create ready lifecycle',()=>assert.equal(createLifecycleRecordFromEnvelope({envelope:env,now:NOW}).status,'created'))
test('3 create dry lifecycle',()=>assert.equal(createLifecycleRecordFromEnvelope({envelope:dry,now:NOW}).status,'execution_simulated'))
test('4 merge pending',()=>assert.equal(mergeApprovalIntoLifecycle({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalRequest:req('pending'),now:NOW}).status,'approval_pending'))
test('5 merge approved',()=>assert.equal(mergeApprovalIntoLifecycle({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalRequest:req('approved'),now:NOW}).status,'approved'))
test('6 merge rejected',()=>assert.equal(mergeApprovalIntoLifecycle({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalRequest:req('rejected'),now:NOW}).status,'rejected'))
test('7 store save/get',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();const l=createLifecycleRecordFromEnvelope({envelope:env,now:NOW});await s.saveLifecycle(l);assert.equal((await s.getLifecycle(l.id))?.id,l.id)})
test('8 get by envelope',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();const l=createLifecycleRecordFromEnvelope({envelope:env,now:NOW});await s.saveLifecycle(l);assert.equal((await s.getLifecycleByEnvelopeId(env.id))?.id,l.id)})
test('9 deterministic lifecycle listing',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();await s.saveLifecycle(createLifecycleRecordFromEnvelope({envelope:{...env,id:'b'},now:NOW}));await s.saveLifecycle(createLifecycleRecordFromEnvelope({envelope:{...env,id:'a'},now:NOW}));assert.deepEqual((await s.listLifecycles()).map(x=>x.envelopeId),['a','b'])})
test('10 deterministic event listing',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();await s.saveEvent(buildLifecycleEvent({lifecycleId:'l',eventType:'execution_ready',message:'x',now:NOW}));await s.saveEvent(buildLifecycleEvent({lifecycleId:'l',eventType:'approval_requested',message:'x',now:NOW}));assert.deepEqual((await s.listEvents()).map(x=>x.eventType),['approval_requested','execution_ready'])})
test('11 approval transition pending',()=>assert.equal(deriveLifecycleTransitionFromApproval({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalRequest:req('pending')})?.eventType,'approval_requested'))
test('12 approval transition approved',()=>assert.equal(deriveLifecycleTransitionFromApproval({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalRequest:req('approved')})?.toStatus,'approved'))
test('13 execution transition executable',()=>assert.equal(deriveExecutionReadinessTransition({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalWorkflowReport:{executableEnvelopeIds:[env.id],blockedEnvelopeIds:[],generatedAt:NOW,totalEnvelopes:1,approvalRequiredCount:0,pendingCount:0,approvedCount:0,rejectedCount:0,blockedCount:0,requests:[],decisions:[],warnings:[],executiveSummary:''}})?.toStatus,'ready_for_execution'))
test('14 execution transition blocked',()=>assert.equal(deriveExecutionReadinessTransition({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalWorkflowReport:{executableEnvelopeIds:[],blockedEnvelopeIds:[env.id],generatedAt:NOW,totalEnvelopes:1,approvalRequiredCount:0,pendingCount:0,approvedCount:0,rejectedCount:0,blockedCount:0,requests:[],decisions:[],warnings:[],executiveSummary:''}})?.toStatus,'execution_blocked'))
test('15 lifecycle event id deterministic',()=>assert.equal(buildLifecycleEvent({lifecycleId:'a',eventType:'execution_ready',message:'x',now:NOW}).id,'lifecycle-event:a:execution_ready:1779796800000'))
test('16 event from transition metadata',()=>assert.equal(buildEventFromTransition({transition:{lifecycleId:'l',fromStatus:'created',toStatus:'approved',eventType:'approval_approved',reason:'r'},now:NOW}).metadata.toStatus,'approved'))
test('17 reconcile approval event',()=>assert.equal(reconcileDashboardTaskLifecycle({lifecycle:{...createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalRequest:req('pending')},now:NOW}).events[0].eventType,'approval_requested'))
test('18 reconcile execution event',()=>assert.equal(reconcileDashboardTaskLifecycle({lifecycle:createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),approvalWorkflowReport:{executableEnvelopeIds:[env.id],blockedEnvelopeIds:[],generatedAt:NOW,totalEnvelopes:1,approvalRequiredCount:0,pendingCount:0,approvedCount:0,rejectedCount:0,blockedCount:0,requests:[],decisions:[],warnings:[],executiveSummary:''},now:NOW}).events[0].eventType,'execution_ready'))
test('19 runtime creates lifecycle',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();const r=await runDashboardTaskLifecyclePersistence({manualPushReport:{mode:'ready',generatedAt:NOW,totalProjections:1,eligibleCount:1,ineligibleCount:0,envelopeCount:1,simulatedCount:0,skippedCount:0,envelopes:[env],simulations:[],warnings:[],executiveSummary:''},store:s,now:NOW});assert.equal(r.totalLifecycles,1)})
test('20 runtime no duplicate envelope_created',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();const report={mode:'ready',generatedAt:NOW,totalProjections:1,eligibleCount:1,ineligibleCount:0,envelopeCount:1,simulatedCount:0,skippedCount:0,envelopes:[env],simulations:[],warnings:[],executiveSummary:''};await runDashboardTaskLifecyclePersistence({manualPushReport:report,store:s,now:NOW});await runDashboardTaskLifecyclePersistence({manualPushReport:report,store:s,now:NOW});assert.equal((await s.listEvents()).filter(e=>e.eventType==='envelope_created').length,1)})
test('21 runtime marks ready',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();const rep=await runDashboardTaskLifecyclePersistence({manualPushReport:{mode:'ready',generatedAt:NOW,totalProjections:1,eligibleCount:1,ineligibleCount:0,envelopeCount:1,simulatedCount:0,skippedCount:0,envelopes:[env],simulations:[],warnings:[],executiveSummary:''},approvalWorkflowReport:{generatedAt:NOW,totalEnvelopes:1,approvalRequiredCount:1,pendingCount:0,approvedCount:1,rejectedCount:0,blockedCount:0,requests:[req('approved')],decisions:[],executableEnvelopeIds:[env.id],blockedEnvelopeIds:[],warnings:[],executiveSummary:''},store:s,now:NOW});assert.equal(rep.readyForExecution,1)})
test('22 runtime marks blocked',async()=>{const s=createInMemoryDashboardTaskLifecycleStore();const rep=await runDashboardTaskLifecyclePersistence({manualPushReport:{mode:'ready',generatedAt:NOW,totalProjections:1,eligibleCount:1,ineligibleCount:0,envelopeCount:1,simulatedCount:0,skippedCount:0,envelopes:[env],simulations:[],warnings:[],executiveSummary:''},approvalWorkflowReport:{generatedAt:NOW,totalEnvelopes:1,approvalRequiredCount:1,pendingCount:1,approvedCount:0,rejectedCount:0,blockedCount:1,requests:[req('pending')],decisions:[],executableEnvelopeIds:[],blockedEnvelopeIds:[env.id],warnings:[],executiveSummary:''},store:s,now:NOW});assert.equal(rep.blocked,1)})
test('23 report ready count',()=>assert.equal(buildDashboardTaskLifecycleReport({generatedAt:NOW,lifecycles:[{...createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),status:'ready_for_execution'}],events:[]}).readyForExecution,1))
test('24 report blocked count',()=>assert.equal(buildDashboardTaskLifecycleReport({generatedAt:NOW,lifecycles:[{...createLifecycleRecordFromEnvelope({envelope:env,now:NOW}),status:'execution_blocked'}],events:[]}).blocked,1))
test('25 report simulated count',()=>assert.equal(buildDashboardTaskLifecycleReport({generatedAt:NOW,lifecycles:[createLifecycleRecordFromEnvelope({envelope:dry,now:NOW})],events:[]}).simulated,1))
