"use server";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { requireAuthenticatedUser } from "@/lib/security/server-authorization";
import { requireWorkspaceRole } from "@/lib/security/access-guards";
import { createCapabilityRequest } from "@/lib/security/capability-flow";
import { evaluatePolicyDecision } from "@/lib/security/policy-engine";
import { evaluateAgentAccess } from "@/lib/security/agent-access";
import { resolveUserAocActorContext } from "@/lib/aoc/actor-context";
const DEMO_TAG = "playground-demo";
async function workspaceContext(){const { user } = await requireAuthenticatedUser(); const supabase=await createSupabaseServerClient(); const {data:membership}=await supabase.from("workspace_memberships").select("workspace_id,role").eq("user_id",user.id).limit(1).maybeSingle<{workspace_id:string;role:string}>(); if(!membership) throw new Error("No workspace"); return {user,workspaceId:membership.workspace_id,supabase};}
export async function createRequestAction(formData:FormData){const {workspaceId}=await workspaceContext(); await createCapabilityRequest({workspaceId,targetResourceType:"project",targetResourceId:String(formData.get("resourceId")??""),requestedPermission:String(formData.get("permission")??"read") as "read" | "write" | "approve" | "manage" | "execute" | "delegate",requestedScope:{workspaceId,demoTag:DEMO_TAG},justification:String(formData.get("justification")??"demo"),expiresAt:String(formData.get("expiresAt")??"")||null}); redirect('/playground?request=1');}
export async function evaluatePolicyAction(formData:FormData){const {user,workspaceId}=await workspaceContext(); const actor=resolveUserAocActorContext(user,{workspaceId}); const d=await evaluatePolicyDecision({actor,workspaceId,resourceType:"project",resourceId:String(formData.get("resourceId")??""),permission:(String(formData.get("permission")??"read") === "write" ? "write" : "read"),justification:String(formData.get("justification")??"demo"),rbacAllowed:false}); redirect('/playground?evaluated='+encodeURIComponent(JSON.stringify(d)));}
export async function simulateAgentAccessAction(formData:FormData){const {workspaceId}=await workspaceContext(); const d=await evaluateAgentAccess({workspaceId,agentId:String(formData.get("agentId")??""),resourceType:"project",resourceId:String(formData.get("resourceId")??""),permission:String(formData.get("permission")??"read") as "read" | "write" | "execute_ai_action"}); redirect('/playground?agent='+encodeURIComponent(JSON.stringify(d)));}
export async function simulateExpirationAction(){const {workspaceId,supabase}=await workspaceContext(); await requireWorkspaceRole(workspaceId,["owner","admin"]); const now=new Date().toISOString(); await supabase.from("capability_grants").update({status:"expired",expires_at:now}).eq("workspace_id",workspaceId).eq("status","active").contains("scope",{demoTag:DEMO_TAG}); redirect('/playground?expired=1');}
export async function resetSandboxAction(){const {workspaceId,user,supabase}=await workspaceContext(); await requireWorkspaceRole(workspaceId,["owner","admin"]); await supabase.from("capability_grants").update({status:"revoked",revoked_at:new Date().toISOString(),revoked_by_user_id:user.id}).eq("workspace_id",workspaceId).contains("scope",{demoTag:DEMO_TAG}); redirect('/playground?reset=1');}
