import { createSupabaseServerClient } from "@/lib/supabase/server";
import { loadRuntimeConversationState } from "@/lib/runtime-conversation-state";
import type { VaultNutrientType } from "@/lib/vault/digestive/types";
const DEFAULT_LIMIT = 18; const MAX_LIMIT = 32; const STALE_DAYS = 30;
type ContinuitySource = "vault_nutrient" | "session_memory";
type ContinuityType = VaultNutrientType | "session_blocker" | "session_stakeholder" | "session_evidence";
export type OperationalContinuityRetrievalInput = { companyId:string; workspaceId:string|null; projectId:string|null; sessionKey?:string; activeDomain?:string; limit?:number; now?:string; includeSessionMemory?:boolean; includeVaultNutrients?:boolean; };
export type OperationalContinuityItem = { id:string; type:ContinuityType; source:ContinuitySource; summary:string; excerpt:string; projectId:string|null; workspaceId:string|null; sessionKey?:string; evidenceRef?:string; createdAt:string; observedAt:string; score:number; rankingBasis:string[]; confidence:"low"|"medium"|"high"; recurrenceCount?:number; stale:boolean; };
export type OperationalContinuityBrief = { topBlockers:string[]; topRisks:string[]; recentDecisions:string[]; stakeholderSignals:string[]; activeCommitments:string[]; unresolvedAmbiguities:string[]; continuityNotes:string[]; confidenceBasis:string[]; limits:string[]; };
export type OperationalContinuityRetrievalResult = { items:OperationalContinuityItem[]; brief:OperationalContinuityBrief; diagnostics:{ retrievedFromVault:number; retrievedFromSessionState:number; suppressedDuplicates:number; staleItemsSuppressed:number; confidenceBasis:string[]; }; };
const nutrientBase: Record<string, number> = { blocker_signal:28, risk_signal:24, escalation_signal:24, financial_impediment_signal:22, governance_gap_signal:22, delivery_drift_signal:20, dependency_signal:19, timeline_pressure_signal:18, contradiction_signal:16, ambiguity_signal:15, commitment_signal:14, decision_signal:13, stakeholder_signal:11, recovery_signal:8 };
const domainBoosts: Record<string, string[]> = { risk:["risk_signal","blocker_signal","delivery_drift_signal"], stakeholder:["stakeholder_signal","escalation_signal","decision_signal"], scope:["ambiguity_signal","contradiction_signal","decision_signal"], execution:["dependency_signal","commitment_signal","blocker_signal"] };
const normalize = (v:string) => v.toLowerCase().replace(/[^a-z0-9\s]/g," ").replace(/\s+/g," ").trim();
const conf = (n:number):OperationalContinuityItem["confidence"] => (n>=75?"high":n>=50?"medium":"low");
export function rankContinuityItems(items: OperationalContinuityItem[], input: OperationalContinuityRetrievalInput): OperationalContinuityItem[] { const now=Date.parse(input.now ?? new Date().toISOString()); const activeDomain=(input.activeDomain??"").toLowerCase(); return items.map((item)=>{ const ageDays=Math.max(0,(now-Date.parse(item.observedAt))/86400000); const recencyScore=Math.max(0,30-ageDays); const stale=ageDays>STALE_DAYS; const domainScore=domainBoosts[activeDomain]?.includes(item.type)?8:0; const evidenceScore=(item.excerpt?6:0)+(item.evidenceRef?5:0)+(/\d{4}-\d{2}-\d{2}|actor|owner/i.test(item.summary)?3:0); const recurrenceScore=Math.min(10,(item.recurrenceCount??1)*2); const sessionScore=input.sessionKey && item.sessionKey===input.sessionKey?4:0; const base=nutrientBase[item.type]??10; const score=Number((base+recencyScore+domainScore+evidenceScore+recurrenceScore+sessionScore).toFixed(2)); return { ...item, score, stale, rankingBasis:[`recency:${recencyScore.toFixed(2)}`,`base:${base}`,`domain:${domainScore}`,`evidence:${evidenceScore}`,`recurrence:${recurrenceScore}`,`session:${sessionScore}`], confidence:conf(score)}; }).sort((a,b)=>b.score-a.score||Date.parse(b.observedAt)-Date.parse(a.observedAt)||a.id.localeCompare(b.id)); }
export function groupContinuityByDomain(items: OperationalContinuityItem[]): Record<string, OperationalContinuityItem[]> { return items.reduce<Record<string, OperationalContinuityItem[]>>((acc,item)=>{ const key=item.type.includes("risk")||item.type.includes("blocker")?"risk":item.type.includes("stakeholder")||item.type.includes("escalation")?"stakeholder":item.type.includes("ambiguity")||item.type.includes("contradiction")?"scope":"execution"; (acc[key]??=[]).push(item); return acc; },{}); }
export function buildContinuityBrief(items: OperationalContinuityItem[], confidenceBasis: string[] = []): OperationalContinuityBrief { const pick=(types:string[])=>items.filter((i)=>types.includes(i.type)).map((i)=>i.summary).slice(0,3); return { topBlockers:pick(["blocker_signal","dependency_signal","session_blocker"]), topRisks:pick(["risk_signal","delivery_drift_signal","timeline_pressure_signal","financial_impediment_signal","governance_gap_signal"]), recentDecisions:pick(["decision_signal"]), stakeholderSignals:pick(["stakeholder_signal","escalation_signal","session_stakeholder"]), activeCommitments:pick(["commitment_signal","recovery_signal"]), unresolvedAmbiguities:pick(["ambiguity_signal","contradiction_signal"]), continuityNotes:[items.length?`Retrieved ${items.length} continuity items in scoped context.`:"No scoped continuity items were retrieved."], confidenceBasis, limits:["Deterministic retrieval only; no semantic inference.","Scope constrained to company/workspace/project."] }; }
export async function retrieveOperationalContinuity(input: OperationalContinuityRetrievalInput): Promise<OperationalContinuityRetrievalResult> { const limit=Math.max(1,Math.min(input.limit??DEFAULT_LIMIT,MAX_LIMIT)); const raw:OperationalContinuityItem[]=[]; let retrievedFromVault=0; let retrievedFromSessionState=0; const confidenceBasis:string[]=[]; if ((input.includeSessionMemory??true) && input.sessionKey){ const state=await loadRuntimeConversationState({ companyId:input.companyId, workspaceId:input.workspaceId, projectId:input.projectId, sessionKey:input.sessionKey }); if (state){ retrievedFromSessionState+=1; for (const v of state.recentBlockers.slice(0,4)) raw.push({id:`session_blocker:${v}`,type:"session_blocker",source:"session_memory",summary:`Recent blocker: ${v}`,excerpt:v,projectId:input.projectId,workspaceId:input.workspaceId,sessionKey:state.sessionKey,createdAt:state.lastSeenAt,observedAt:state.lastSeenAt,score:0,rankingBasis:[],confidence:"low",stale:false}); for (const v of state.recentStakeholders.slice(0,3)) raw.push({id:`session_stakeholder:${v}`,type:"session_stakeholder",source:"session_memory",summary:`Stakeholder continuity: ${v}`,excerpt:v,projectId:input.projectId,workspaceId:input.workspaceId,sessionKey:state.sessionKey,createdAt:state.lastSeenAt,observedAt:state.lastSeenAt,score:0,rankingBasis:[],confidence:"low",stale:false}); for (const v of state.recentEvidence.slice(0,3)) raw.push({id:`session_evidence:${v}`,type:"session_evidence",source:"session_memory",summary:`Recent evidence: ${v}`,excerpt:v,projectId:input.projectId,workspaceId:input.workspaceId,sessionKey:state.sessionKey,createdAt:state.lastSeenAt,observedAt:state.lastSeenAt,score:0,rankingBasis:[],confidence:"low",stale:false}); confidenceBasis.push(`session_memory:messageCount=${state.messageCount}`); } }
if ((input.includeVaultNutrients??true) && input.workspaceId){ const supabase=await createSupabaseServerClient(); let query=supabase.from("vault_nutrients").select("id,nutrient_type,summary,evidence,created_at,project_id,workspace_id,company_id").eq("company_id",input.companyId).eq("workspace_id",input.workspaceId).order("created_at",{ascending:false}).limit(120); if (input.projectId) query=query.eq("project_id",input.projectId); if (!input.projectId) query=query.is("project_id",null); const {data,error}=await query; if (error) throw new Error(`operational_continuity_vault_query_failed:${error.message}`); for (const row of (data??[]) as Array<Record<string,unknown>>){ retrievedFromVault+=1; const evidence=Array.isArray(row.evidence)?row.evidence as Array<Record<string,unknown>>:[]; const excerpt=String((evidence[0]?.excerpt as string|undefined)??row.summary??"").slice(0,220); raw.push({id:String(row.id),type:String(row.nutrient_type) as ContinuityType,source:"vault_nutrient",summary:String(row.summary??""),excerpt,projectId:(row.project_id as string|null)??null,workspaceId:(row.workspace_id as string|null)??null,sessionKey:typeof evidence[0]?.sourceReference==="string"?String(evidence[0]?.sourceReference):undefined,evidenceRef:typeof evidence[0]?.sourceArtifactId==="string"?String(evidence[0]?.sourceArtifactId):undefined,createdAt:String(row.created_at),observedAt:String(row.created_at),score:0,rankingBasis:[],confidence:"low",recurrenceCount:1,stale:false}); } confidenceBasis.push("vault_nutrients:scoped_query"); }
const dedup=new Map<string,OperationalContinuityItem>(); let suppressedDuplicates=0; for (const item of raw){ const key=`${normalize(item.excerpt).slice(0,120)}|${item.type}|${item.projectId??"none"}`; const found=dedup.get(key); if (!found) dedup.set(key,item); else { found.recurrenceCount=(found.recurrenceCount??1)+1; suppressedDuplicates+=1; } }
const ranked=rankContinuityItems(Array.from(dedup.values()),input); const staleItemsSuppressed=ranked.filter((item)=>item.stale).length; const bounded=ranked.filter((item)=>!item.stale).slice(0,limit); const brief=buildContinuityBrief(bounded,confidenceBasis); return { items:bounded, brief, diagnostics:{ retrievedFromVault, retrievedFromSessionState, suppressedDuplicates, staleItemsSuppressed, confidenceBasis } }; }
