import type {
  PMOGovernanceSkeleton,
  PMORole,
  DeliveryControl,
  EscalationRule,
} from "./pmo-governance-types";

export const DEFAULT_ROLES: PMORole[] = [
  {
    id: "role-0",
    roleName: "PMO Lead",
    personName: "",
    email: "",
    responsibility: "Governance oversight and PMO operations",
    approvalAuthority: true,
    escalationAuthority: true,
  },
  {
    id: "role-1",
    roleName: "Project Manager",
    personName: "",
    email: "",
    responsibility: "Day-to-day project execution and coordination",
    approvalAuthority: true,
    escalationAuthority: true,
  },
  {
    id: "role-2",
    roleName: "Technical Lead",
    personName: "",
    email: "",
    responsibility: "Technical decisions and architecture",
    approvalAuthority: true,
    escalationAuthority: false,
  },
  {
    id: "role-3",
    roleName: "Finance Lead",
    personName: "",
    email: "",
    responsibility: "Budget control and financial approvals",
    approvalAuthority: true,
    escalationAuthority: false,
  },
  {
    id: "role-4",
    roleName: "Logistics / Procurement",
    personName: "",
    email: "",
    responsibility: "Vendor management and procurement",
    approvalAuthority: false,
    escalationAuthority: false,
  },
  {
    id: "role-5",
    roleName: "Executive Sponsor",
    personName: "",
    email: "",
    responsibility: "Strategic direction and executive decisions",
    approvalAuthority: true,
    escalationAuthority: true,
  },
  {
    id: "role-6",
    roleName: "Client Owner",
    personName: "",
    email: "",
    responsibility: "Client relationship and acceptance",
    approvalAuthority: true,
    escalationAuthority: false,
  },
  {
    id: "role-7",
    roleName: "Vendor Owner",
    personName: "",
    email: "",
    responsibility: "Vendor performance and delivery",
    approvalAuthority: false,
    escalationAuthority: false,
  },
];

export const DEFAULT_DELIVERY_CONTROLS: DeliveryControl[] = [
  {
    id: "ctrl-0",
    name: "Scope Control",
    enabled: true,
    ownerRole: "Project Manager",
    reviewFrequency: "weekly",
    requiredEvidence: "Scope change log",
    escalationThreshold: "Any unapproved scope change",
  },
  {
    id: "ctrl-1",
    name: "Timeline Control",
    enabled: true,
    ownerRole: "Project Manager",
    reviewFrequency: "weekly",
    requiredEvidence: "Updated schedule baseline",
    escalationThreshold: ">10% schedule variance",
  },
  {
    id: "ctrl-2",
    name: "Cost Control",
    enabled: true,
    ownerRole: "Finance Lead",
    reviewFrequency: "monthly",
    requiredEvidence: "Budget vs actual report",
    escalationThreshold: ">5% budget variance",
  },
  {
    id: "ctrl-3",
    name: "Risk / RAID Control",
    enabled: true,
    ownerRole: "Project Manager",
    reviewFrequency: "weekly",
    requiredEvidence: "RAID log",
    escalationThreshold: "Any unmitigated critical risk",
  },
  {
    id: "ctrl-4",
    name: "Stakeholder Control",
    enabled: true,
    ownerRole: "PMO Lead",
    reviewFrequency: "biweekly",
    requiredEvidence: "Stakeholder engagement log",
    escalationThreshold: "Stakeholder dissatisfaction flagged",
  },
  {
    id: "ctrl-5",
    name: "Change Control",
    enabled: true,
    ownerRole: "PMO Lead",
    reviewFrequency: "per-milestone",
    requiredEvidence: "Approved change request",
    escalationThreshold: "Unapproved change implemented",
  },
  {
    id: "ctrl-6",
    name: "Acceptance Control",
    enabled: true,
    ownerRole: "Client Owner",
    reviewFrequency: "per-milestone",
    requiredEvidence: "Signed acceptance criteria",
    escalationThreshold: "Acceptance blocked >48 hours",
  },
  {
    id: "ctrl-7",
    name: "Documentation Control",
    enabled: false,
    ownerRole: "Project Manager",
    reviewFrequency: "monthly",
    requiredEvidence: "Document register",
    escalationThreshold: "Missing required documents",
  },
];

export const DEFAULT_ESCALATION_RULES: EscalationRule[] = [
  {
    id: "esc-0",
    triggerName: "Client dependency blocked",
    enabled: true,
    severity: "high",
    firstAction: "Notify Client Owner and PM immediately",
    escalateToRole: "PMO Lead",
    timeThreshold: "24-hours",
    suggestedTone: "diplomatic",
  },
  {
    id: "esc-1",
    triggerName: "Vendor delay",
    enabled: true,
    severity: "medium",
    firstAction: "Issue formal delay notification to vendor",
    escalateToRole: "Logistics / Procurement",
    timeThreshold: "48-hours",
    suggestedTone: "direct",
  },
  {
    id: "esc-2",
    triggerName: "Financial approval pending",
    enabled: true,
    severity: "high",
    firstAction: "Escalate approval request to Finance Lead",
    escalateToRole: "Finance Lead",
    timeThreshold: "24-hours",
    suggestedTone: "direct",
  },
  {
    id: "esc-3",
    triggerName: "Scope ambiguity",
    enabled: true,
    severity: "medium",
    firstAction: "Convene scope clarification session",
    escalateToRole: "PMO Lead",
    timeThreshold: "48-hours",
    suggestedTone: "diplomatic",
  },
  {
    id: "esc-4",
    triggerName: "Timeline at risk",
    enabled: true,
    severity: "high",
    firstAction: "Issue timeline risk alert and recovery plan",
    escalateToRole: "Executive Sponsor",
    timeThreshold: "same-day",
    suggestedTone: "executive",
  },
  {
    id: "esc-5",
    triggerName: "Stakeholder misalignment",
    enabled: true,
    severity: "medium",
    firstAction: "Schedule alignment meeting with sponsors",
    escalateToRole: "PMO Lead",
    timeThreshold: "48-hours",
    suggestedTone: "diplomatic",
  },
  {
    id: "esc-6",
    triggerName: "Missing access / credentials",
    enabled: true,
    severity: "medium",
    firstAction: "Request access through IT / admin channel",
    escalateToRole: "Technical Lead",
    timeThreshold: "24-hours",
    suggestedTone: "direct",
  },
  {
    id: "esc-7",
    triggerName: "Acceptance blocked",
    enabled: true,
    severity: "critical",
    firstAction: "Emergency meeting with Client Owner",
    escalateToRole: "Executive Sponsor",
    timeThreshold: "same-day",
    suggestedTone: "urgent",
  },
  {
    id: "esc-8",
    triggerName: "Critical risk unresolved",
    enabled: true,
    severity: "critical",
    firstAction: "Invoke risk response plan immediately",
    escalateToRole: "PMO Lead",
    timeThreshold: "same-day",
    suggestedTone: "urgent",
  },
];

export const INITIAL_PMO_SKELETON: Omit<PMOGovernanceSkeleton, "createdAt" | "updatedAt"> = {
  identity: {
    name: "",
    organization: "",
    pmoType: "",
    industry: "",
    language: "",
    timeZone: "",
  },
  governanceModel: {
    governanceStyle: "",
    approvalModel: "",
    reportingCadence: "",
    escalationCadence: "",
  },
  roles: DEFAULT_ROLES,
  deliveryControls: DEFAULT_DELIVERY_CONTROLS,
  escalationRules: DEFAULT_ESCALATION_RULES,
};
