import type { OperationalMemoryScope } from "../runtime-memory-types";

export type EvidenceBoundTwin = { evidence: string[]; confidence: number; uncertainty: string[]; causalityRationale: string[]; survivabilityRationale: string[]; governanceBoundaries: string[] };
export type OrganizationalHealthState = "stable"|"pressured"|"degraded"|"unstable"|"critical"|"recovering"|"stabilized"|"collapse_risk";
export type OrganizationalDigitalTwinRequest = { scope: OperationalMemoryScope; now?: string; limit?: number };
export type OrganizationalTopologyNode = { id: string; type: "project"|"stakeholder"|"pm"|"governance"|"delivery"|"dependency"; label: string; pressureScore: number };
export type OrganizationalTopologyEdge = { from: string; to: string; relation: "escalates_to"|"depends_on"|"governs"|"delivers_for"|"blocks"; weight: number };
export type OrganizationalTopologyGraph = EvidenceBoundTwin & { nodes: OrganizationalTopologyNode[]; edges: OrganizationalTopologyEdge[]; bottlenecks: string[]; pressureZones: string[] };
export type OrganizationalPressureFlow = EvidenceBoundTwin & { source: string; target: string; intensity: number; vector: string };
export type OrganizationalPropagationPath = EvidenceBoundTwin & { id: string; path: string[]; propagationType: string; probability: number; containmentLevers: string[] };
export type OrganizationalSurvivabilityState = EvidenceBoundTwin & { milestoneSurvivability: number; portfolioSurvivability: number; pmSurvivability: number; operationalSurvivability: number; recoverySurvivability: number; stabilizationProbability: number };
export type OrganizationalCollapseRisk = EvidenceBoundTwin & { riskScore: number; zones: string[] };
export type OrganizationalRecoveryState = EvidenceBoundTwin & { recoveryScore: number; blockers: string[]; enablers: string[] };
export type OrganizationalStabilizationState = EvidenceBoundTwin & { trajectory: "improving"|"plateauing"|"false_stabilization"|"collapsing"; fatigueRisk: number; escalationExhaustion: number };
export type OrganizationalInterventionSimulation = EvidenceBoundTwin & { id: string; sequence: string[]; survivabilityImprovement: number; pressureReduction: number; propagationReduction: number; recoveryAcceleration: number; escalationContainment: number };
export type OrganizationalScenarioProjection = EvidenceBoundTwin & { scenario: string; likelyFutureState: OrganizationalHealthState; probabilityShift: number };
export type OrganizationalStateTransition = EvidenceBoundTwin & { from: OrganizationalHealthState; to: OrganizationalHealthState; trigger: string };
export type OrganizationalFragilitySignal = EvidenceBoundTwin & { signal: string; category: string; fragilityScore: number };
export type OrganizationalEvolutionSnapshot = EvidenceBoundTwin & { timestamp: string; state: OrganizationalHealthState; survivability: number; pressure: number; note: string };
export type OrganizationalSimulationNarrative = EvidenceBoundTwin & { narrative: string };
export type OrganizationalTwinDiagnostic = EvidenceBoundTwin & { topic: string; whyChanged: string[] };
export type OrganizationalWarRoomState = EvidenceBoundTwin & { instabilityMap: string[]; collapseRiskZones: string[]; pmOverloadMap: string[]; stabilizationTrajectory: OrganizationalStabilizationState; topInterventions: OrganizationalInterventionSimulation[] };
export type OrganizationalTwinState = EvidenceBoundTwin & { state: OrganizationalHealthState; pressure: number; governanceErosion: number; pmOverload: number; criticalPathFragility: number };
export type OrganizationalDigitalTwinResult = {
  state: OrganizationalTwinState;
  topology: OrganizationalTopologyGraph;
  pressureFlows: OrganizationalPressureFlow[];
  propagation: OrganizationalPropagationPath[];
  survivability: OrganizationalSurvivabilityState;
  collapseRisk: OrganizationalCollapseRisk;
  recovery: OrganizationalRecoveryState;
  stabilization: OrganizationalStabilizationState;
  interventions: OrganizationalInterventionSimulation[];
  scenarios: OrganizationalScenarioProjection[];
  transitions: OrganizationalStateTransition[];
  fragility: OrganizationalFragilitySignal[];
  evolution: OrganizationalEvolutionSnapshot[];
  warRoom: OrganizationalWarRoomState;
  narratives: OrganizationalSimulationNarrative[];
  diagnostics: OrganizationalTwinDiagnostic[];
};
