import { createHash, randomBytes } from "node:crypto";
import { createPrivilegedSupabaseClient } from "@/lib/security/privileged-access";
import { logSecurityEvent } from "@/lib/security/telemetry";
import { createCapabilityClaim, claimToAuditMetadata, hashCapabilityClaim } from "@/lib/security/capability-claims";

const hashToken = (token: string) => createHash("sha256").update(token).digest("hex");
export const generateExecutionGrantToken = () => randomBytes(32).toString("base64url");

type ExecutionGrantInput = { workspaceId: string; approvalRequestId?: string; decisionId?: string; projectId?: string | null; actorUserId?: string | null; actorAgentId?: string | null; action: string; requestedPermission: string; resourceType?: string | null; resourceId?: string | null; issuedByUserId?: string | null; ttlMs?: number; metadata?: Record<string, unknown>; grantToken?: string };

export async function issueExecutionGrant(input: ExecutionGrantInput) {
  const grantToken = generateExecutionGrantToken();
  const supabase = createPrivilegedSupabaseClient({ routeId: "governance.execution_grants.issue", operation: "issue_execution_grant", reason: "approved_governance_action", systemActor: "system", workspaceId: input.workspaceId, actorUserId: input.issuedByUserId ?? null });
  const payload = { approval_request_id: input.approvalRequestId, decision_id: input.decisionId, workspace_id: input.workspaceId, project_id: input.projectId ?? null, actor_user_id: input.actorUserId ?? null, actor_agent_id: input.actorAgentId ?? null, action: input.action, requested_permission: input.requestedPermission, resource_type: input.resourceType ?? null, resource_id: input.resourceId ?? null, grant_token_hash: hashToken(grantToken), status: "active", issued_by_user_id: input.issuedByUserId ?? null, issued_at: new Date().toISOString(), expires_at: new Date(Date.now() + (input.ttlMs ?? 15 * 60 * 1000)).toISOString(), metadata: input.metadata ?? {} };
  const { data, error } = await supabase.from("governance_execution_grants").upsert(payload, { onConflict: "approval_request_id", ignoreDuplicates: true }).select("*").single();
  if (error) throw new Error(`issue execution grant failed: ${error.message}`);
  await logSecurityEvent("execution_grant_issued", { workspaceId: data.workspace_id, projectId: data.project_id, actorUserId: data.actor_user_id, actorAgentId: data.actor_agent_id, requested_permission: data.requested_permission, metadata: { grantId: data.id, decisionId: data.decision_id, approvalRequestId: data.approval_request_id, action: data.action, status: data.status, reason: "approved" } });
  const claim = await createCapabilityClaim({
    issuer: { app: "pmfreak", workspaceId: data.workspace_id, issuerType: "system", issuerUserId: input.issuedByUserId ?? undefined },
    subject: data.actor_agent_id ? { subjectType: "agent", agentId: data.actor_agent_id } : { subjectType: "user", userId: data.actor_user_id ?? undefined },
    authority: { action: data.action, requestedPermission: data.requested_permission, resourceType: data.resource_type ?? undefined, resourceId: data.resource_id ?? undefined, workspaceId: data.workspace_id, projectId: data.project_id ?? undefined },
    constraints: { allowedUntil: data.expires_at, canDelegate: false },
    lineage: { parentDecisionId: data.decision_id ?? undefined, rootApprovalRequestId: data.approval_request_id ?? undefined, issuedAt: data.issued_at },
  });
  await logSecurityEvent("capability_claim_issued", { workspaceId: data.workspace_id, projectId: data.project_id, actorUserId: data.actor_user_id, actorAgentId: data.actor_agent_id, requested_permission: data.requested_permission, metadata: { ...claimToAuditMetadata(claim, "execution_grant") } });
  return { grant: data, grantToken, capabilityClaim: claim };
}

export async function validateExecutionGrant(input: ExecutionGrantInput) { const supabase = createPrivilegedSupabaseClient({ routeId: "governance.execution_grants.validate", operation: "validate_execution_grant", reason: "pre_execution_validation", systemActor: "system", workspaceId: input.workspaceId, actorUserId: input.actorUserId ?? null }); const { data } = await supabase.from("governance_execution_grants").select("*").eq("grant_token_hash", hashToken(input.grantToken ?? "")).maybeSingle(); if (!data) return { ok: false, reason: "not_found" }; if (data.status !== "active") return { ok: false, reason: data.status, grant: data }; if (new Date(data.expires_at).getTime() <= Date.now()) return { ok: false, reason: "expired", grant: data }; if (data.workspace_id !== input.workspaceId || (input.projectId && data.project_id && data.project_id !== input.projectId) || data.action !== input.action || data.requested_permission !== input.requestedPermission || (input.resourceType && data.resource_type && data.resource_type !== input.resourceType) || (input.resourceId && data.resource_id && data.resource_id !== input.resourceId) || (input.actorUserId && data.actor_user_id && data.actor_user_id !== input.actorUserId) || (input.actorAgentId && data.actor_agent_id && data.actor_agent_id !== input.actorAgentId)) return { ok: false, reason: "scope_mismatch", grant: data }; return { ok: true, grant: data }; }

export async function consumeExecutionGrant(input: ExecutionGrantInput) { const validation = await validateExecutionGrant(input); if (!validation.ok) return validation; const supabase = createPrivilegedSupabaseClient({ routeId: "governance.execution_grants.consume", operation: "consume_execution_grant", reason: "single_use_execution", systemActor: "system", workspaceId: input.workspaceId, actorUserId: input.actorUserId ?? null }); const now = new Date().toISOString(); const { data } = await supabase.from("governance_execution_grants").update({ status: "consumed", consumed_at: now, consumed_by_user_id: input.actorUserId ?? null, consumed_by_agent_id: input.actorAgentId ?? null }).eq("id", validation.grant.id).eq("status", "active").select("*").maybeSingle(); if (!data) { await logSecurityEvent("execution_grant_replay_attempt", { workspaceId: validation.grant.workspace_id, projectId: validation.grant.project_id, actorUserId: input.actorUserId ?? null, actorAgentId: input.actorAgentId ?? null, requested_permission: validation.grant.requested_permission, metadata: { grantId: validation.grant.id, decisionId: validation.grant.decision_id, approvalRequestId: validation.grant.approval_request_id, action: validation.grant.action, status: "replay_attempt", reason: "already_consumed_or_changed" } }); return { ok: false, reason: "replay_attempt", grant: validation.grant }; } await logSecurityEvent("execution_grant_consumed", { workspaceId: data.workspace_id, projectId: data.project_id, actorUserId: input.actorUserId ?? null, actorAgentId: input.actorAgentId ?? null, requested_permission: data.requested_permission, metadata: { grantId: data.id, decisionId: data.decision_id, approvalRequestId: data.approval_request_id, action: data.action, status: data.status, reason: "consumed" } }); return { ok: true, grant: data }; }
