import { createSupabaseServerClient } from "@/lib/supabase/server";

export default async function GovernancePage() {
  const supabase = await createSupabaseServerClient();
  const { data } = await supabase.from("governance_approval_requests").select("*").order("created_at", { ascending: false }).limit(50);
  const approvalIds = (data ?? []).map((r) => r.id);
  const { data: grants } = approvalIds.length ? await supabase.from("governance_execution_grants").select("approval_request_id, status, expires_at").in("approval_request_id", approvalIds) : { data: [] as Array<{ approval_request_id: string; status: string; expires_at: string | null }> };
  const { data: delegations } = await supabase.from("governance_delegations").select("*").order("created_at", { ascending: false }).limit(50);
  const grantByApproval = new Map((grants ?? []).map((g) => [g.approval_request_id, g]));
  return <main className="p-6 space-y-6"><section><h1 className="text-2xl font-semibold">Approval Inbox</h1><div className="space-y-4 mt-4">{(data ?? []).map((r) => { const grant = grantByApproval.get(r.id); return <div key={r.id} className="border p-3 rounded"><p><b>{r.action}</b> · {r.risk_level}</p><p>Status: <b>{r.status}</b>{r.status === "approved" && !grant ? " (approved, awaiting execution grant)" : ""}</p><p>Requester: {r.actor_user_id ?? r.actor_agent_id ?? "n/a"}</p><p>Grant: {grant ? `${grant.status} · expires ${grant.expires_at ?? "n/a"}` : "none"}</p><p>Reason: {r.reason}</p><details><summary>Trace</summary><pre className="text-xs overflow-auto">{JSON.stringify(r.trace, null, 2)}</pre></details><div className="mt-2 flex gap-2">{r.status === "pending_approval" ? <><form action={`/api/governance/approvals/${r.id}/approve`} method="post"><button className="px-2 py-1 bg-green-600 text-white rounded" type="submit">Approve</button></form><form action={`/api/governance/approvals/${r.id}/reject`} method="post"><button className="px-2 py-1 bg-red-600 text-white rounded" type="submit">Reject</button></form></> : null}</div></div>; })}</div></section><section><h2 className="text-xl font-semibold">Governance Delegations</h2><div className="space-y-3 mt-3">{(delegations ?? []).map((d) => <div key={d.id} className="border p-3 rounded"><p><b>{d.action}</b> · {d.requested_permission}</p><p>Delegatee: {d.delegatee_user_id ?? d.delegatee_agent_id ?? "n/a"}</p><p>Scope: workspace {d.workspace_id} · project {d.project_id ?? "n/a"} · resource {d.resource_type ?? "n/a"}/{d.resource_id ?? "n/a"}</p><p>Uses: {d.uses_count}/{d.max_uses} · Expires: {d.expires_at} · Status: {d.status}</p><p>Parent: grant {d.parent_grant_id ?? "n/a"} · decision {d.parent_decision_id ?? "n/a"}</p><details><summary>Lineage</summary><pre className="text-xs overflow-auto">{JSON.stringify({ parentGrantId: d.parent_grant_id, parentDecisionId: d.parent_decision_id, delegatorUserId: d.delegator_user_id, delegatorAgentId: d.delegator_agent_id, delegateeUserId: d.delegatee_user_id, delegateeAgentId: d.delegatee_agent_id, constraints: d.constraints, expiresAt: d.expires_at }, null, 2)}</pre></details><form action="/api/governance/delegations/revoke" method="post" className="mt-2"><input type="hidden" name="delegationId" value={d.id} /><input type="hidden" name="workspaceId" value={d.workspace_id} /><button className="px-2 py-1 bg-amber-600 text-white rounded" type="submit">Revoke</button></form></div>)}</div></section></main>;
}
